apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulate-service-deployment
  labels:
    app: simulate-service-deployment
spec:
  selector:
    matchLabels:
      app: simulate-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: simulate-service-deployment
    spec:
      containers:
        - name: simulate-service
          image: benjazuniga/simulate-service
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"